### ISSUE TITLE
failed to deserialize BitPay server response (Invoice)

### ISSUE THREAD

**Issue by masudulhasan** [bitpay/android-sdk-sample#4]
I am trying to run the sample app and got this error.  I am using android 6.0.1. 

`12-11 15:23:24.900 17298-17298/com.bitpay.sample.musicstore W/System.err: com.bitpay.sdk.controller.BitPayException: Error - failed to deserialize BitPay server response (Invoice) : Unrecognized field "buyerTotalBtcAmount" (class com.bitpay.sdk.model.Invoice), not marked as ignorable (31 known properties: "itemDesc", "notificationURL", "guid", "price", "transactionSpeed", "orderId", "paymentUrls", "refundAddresses", "buyerFields", "currency", "transactions", "physical", "fullNotifications" [truncated]])
12-11 15:23:24.900 17298-17298/com.bitpay.sample.musicstore W/System.err:     at [Source: {"facade":"pos/invoice","data":{"url":"https://test.bitpay.com/invoice?id=Sce3ko5fKUrov58ZiioPTi","status":"new","btcPrice":"0.075392","btcDue":"0.075396","price":1233.49,"currency":"USD","buyerTotalBtcAmount":"0.075396","invoiceTime":1512984205878,"expirationTime":1512985105878,"currentTime":1512984205893,"guid":"6772972","id":"Sce3ko5fKUrov58ZiioPTi","lowFeeDetected":false,"btcPaid":"0.000000","rate":16361.08,"exceptionStatus":false,"refundAddressRequestPending":false,"addresses":{"BTC":"n2hM4HJCstBmBEZYmoZkhsERJpubukCLxN"},"paymentSubtotals":{"BTC":7539200},"paymentTotals":{"BTC":7539600},"paymentUrls":{"BIP21":"bitcoin:n2hM4HJCstBmBEZYmoZkhsERJpubukCLxN?amount=0.075396","BIP72":"bitcoin:n2hM4HJCstBmBEZYmoZkhsERJpubukCLxN?amount=0.075396&r=https://test.bitpay.com/i/Sce3ko5fKUrov58ZiioPTi","BIP72b":"bitcoin:?r=https://test.bitpay.com/i/Sce3ko5fKUrov58ZiioPTi","BIP73":"https://test.bitpay.com/i/Sce3ko5fKUrov58ZiioPTi"},"bitcoinAddress":"n2hM4HJCstBmBEZYmoZkhsERJpubukCLxN","buyerPaidBtcMinerFee":"0.000004","supportedTransactionCurrencies":{"BTC":{"enabled":true}},"exRates":{"USD":16361.081065668901},"exchangeRates":{"BTC":{"USD":16361.081065668901}},"token":"3BjTnM1C47mHNgZZy2vS6KEeBXRZzu8UBURN3num5sxhBWVprWeC2gSyGPe2PH5Csg"}}; line: 1, column: 212] (through reference chain: com.bitpay.sdk.controller.InvoiceWrapper["data"]->com.bitpay.sdk.model.Invoice["buyerTotalBtcAmount"])
12-11 15:23:24.901 17298-17298/com.bitpay.sample.musicstore W/System.err:     at com.bitpay.sdk.controller.BitPay.createInvoice(BitPay.java:199)
12-11 15:23:24.901 17298-17298/com.bitpay.sample.musicstore W/System.err:     at com.bitpay.sdk.android.BitPayAndroid$CreateInvoiceTask.doInBackground(BitPayAndroid.java:395)
12-11 15:23:24.901 17298-17298/com.bitpay.sample.musicstore W/System.err:     at com.bitpay.sdk.android.BitPayAndroid$CreateInvoiceTask.doInBackground(BitPayAndroid.java:383)
12-11 15:23:24.901 17298-17298/com.bitpay.sample.musicstore W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
12-11 15:23:24.901 17298-17298/com.bitpay.sample.musicstore W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-11 15:23:24.901 17298-17298/com.bitpay.sample.musicstore W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-11 15:23:24.901 17298-17298/com.bitpay.sample.musicstore W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-11 15:23:24.901 17298-17298/com.bitpay.sample.musicstore W/System.err:     at java.lang.Thread.run(Thread.java:818)`

**Comment by solokingjec** [comment]
hello.
Am also having the same issue.

**Comment by AnandanCNA** [comment]
what is the solution

**Comment by AnandanCNA** [comment]
Error - failed to deserialize BitPay server response (Invoice) : Unrecognized field "lowFeeDetected"

**Comment by JefferyHus** [comment]
I can assume that this is because your IP is blocked? Or just the country you are in is blocked
